### PR TITLE
Use -rdynamic instead of list all export

### PR DESCRIPTION
**Pull request by alberic89**
It will help you later when you will add a lot of function to export.

### CODE REVIEW

**Comment by Cugatay** [comment]
Oh, that seems great! I didn't know that. Now there's no need to use such a complex build command with these changes to the build file. I'm gonna change the README.md to suggest people to use `zig build` directly and inform how this works with build file. Than you so much

**Comment by alberic89** [comment]
Be careful, `zig build` produce a wasm binary in the `zig-out/bin` folder. And for why you need to build a wasm binary *and* a library ? How can you use the library ?

**Comment by Cugatay** [comment]
I don't understand the question correctly. Let me answer what I understand
Yeah, it produces the binary in `zig-out/bin`, while the old function created it in the root dir. So, I'm going to move it to react/public, this part doesn't change. So React keeps using the wasm binary in web app.
The only thing that changes is that you won't need to memorize a complex build command in this context. Can I get your opinions?

**Comment by alberic89** [comment]
My question was about this part of the `build.zig` : https://github.com/Cugatay/zig-wasm-react-nodejs/blob/064997d43c8fb2dc8caca094ae233d9983e6f0da/build.zig#L14
Why do you need to create a static library ?

**Comment by Cugatay** [comment]
Oh I understand now. You're right, lib is unnecessary. I'll remove it

I'm just learning build system :)

**Pull request merged**
